# -*- coding: utf-8 -*-
"""Untitled66.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUw-Alq2kXSn_4epNRUGuPZZZhbku_qt
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np
import sklearn.compose._column_transformer

# --- COMPATIBILITY PATCH ---
# This fixes the '_RemainderColsList' error by creating a dummy class
# if the server version of sklearn is missing it.
if not hasattr(sklearn.compose._column_transformer, '_RemainderColsList'):
    class _RemainderColsList:
        pass
    sklearn.compose._column_transformer._RemainderColsList = _RemainderColsList
# ---------------------------

# Set page configuration
st.set_page_config(page_title="Heart Disease Predictor", page_icon="❤️", layout="wide")

st.title("❤️ Heart Disease Prediction System")
st.write("This application uses a Logistic Regression model to predict the risk of heart disease.")

# Load the model
@st.cache_resource
def load_model():
    try:
        return joblib.load('trained_model.joblib')
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

model = load_model()

if model:
    st.sidebar.header("Patient Information")
    st.sidebar.info("Please enter the patient's medical data below.")

    # Input Fields
    with st.container():
        col1, col2, col3 = st.columns(3)

        with col1:
            male = st.selectbox("Gender", options=[1, 0], format_func=lambda x: "Male" if x == 1 else "Female")
            age = st.number_input("Age", min_value=1, max_value=120, value=40)
            education = st.selectbox("Education Level", options=[1, 2, 3, 4], help="1: Some High School, 2: High School/GED, 3: Some College, 4: College Degree")
            currentSmoker = st.radio("Current Smoker?", options=[1, 0], format_func=lambda x: "Yes" if x == 1 else "No")
            cigsPerDay = st.number_input("Cigarettes Per Day", min_value=0, max_value=100, value=0)

        with col2:
            BPMeds = st.selectbox("On BP Medication?", options=[1.0, 0.0], format_func=lambda x: "Yes" if x == 1.0 else "No")
            prevalentStroke = st.selectbox("Previous Stroke?", options=[1, 0], format_func=lambda x: "Yes" if x == 1 else "No")
            prevalentHyp = st.selectbox("Hypertension?", options=[1, 0], format_func=lambda x: "Yes" if x == 1 else "No")
            diabetes = st.selectbox("Diabetes?", options=[1, 0], format_func=lambda x: "Yes" if x == 1 else "No")
            totChol = st.number_input("Total Cholesterol (mg/dL)", min_value=100, max_value=600, value=200)

        with col3:
            sysBP = st.number_input("Systolic Blood Pressure", min_value=80, max_value=250, value=120)
            diaBP = st.number_input("Diastolic Blood Pressure", min_value=40, max_value=150, value=80)
            BMI = st.number_input("BMI", min_value=10.0, max_value=60.0, value=25.0)
            heartRate = st.number_input("Heart Rate (BPM)", min_value=40, max_value=200, value=75)
            glucose = st.number_input("Glucose Level (mg/dL)", min_value=40, max_value=500, value=80)

    # Prediction Logic
    if st.button("Predict Risk"):
        # Create input DataFrame with feature names exactly as trained
        input_df = pd.DataFrame([[
            male, age, education, currentSmoker, cigsPerDay, BPMeds,
            prevalentStroke, prevalentHyp, diabetes, totChol, sysBP,
            diaBP, BMI, heartRate, glucose
        ]], columns=[
            'male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
            'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
            'diaBP', 'BMI', 'heartRate', 'glucose'
        ])

        try:
            prediction = model.predict(input_df)[0]
            probability = model.predict_proba(input_df)[0][1]

            st.divider()
            if prediction == 1:
                st.error(f"### Result: High Risk of Heart Disease")
                st.write(f"Confidence Level: **{probability:.2%}**")
            else:
                st.success(f"### Result: Low Risk of Heart Disease")
                st.write(f"Probability of Risk: **{probability:.2%}**")

            # Show input summary
            with st.expander("Show detailed inputs"):
                st.dataframe(input_df)

        except Exception as e:
            st.error(f"An error occurred during prediction: {e}")