# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lh3ACdS3IdpvbY-iAf-9Y5tWHWTs7L70
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# Page configuration
st.set_page_config(page_title="Heart Disease Risk Predictor", layout="wide")

st.title("🫀 Heart Disease Prediction (Logistic Regression)")
st.write("Fill in the patient details to calculate the risk of heart disease.")

# Load the model with error handling
@st.cache_resource
def load_heart_model():
    try:
        return joblib.load('trained_model.joblib')
    except Exception as e:
        st.error(f"Error loading model: {e}")
        st.info("Ensure 'trained_model.joblib' is in the same folder as this script.")
        return None

model = load_heart_model()

if model:
    # Organize inputs into columns
    with st.form("input_form"):
        col1, col2, col3 = st.columns(3)

        with col1:
            st.subheader("Demographics")
            male = st.selectbox("Gender", options=[1, 0], format_func=lambda x: "Male" if x == 1 else "Female")
            age = st.number_input("Age", min_value=1, max_value=120, value=40)
            education = st.selectbox("Education Level", options=[1, 2, 3, 4], help="1: Some High School, 2: High School/GED, 3: Some College, 4: College Degree")

            st.subheader("Behavioral")
            currentSmoker = st.radio("Current Smoker?", options=[1, 0], format_func=lambda x: "Yes" if x == 1 else "No")
            cigsPerDay = st.number_input("Cigarettes Per Day", min_value=0, max_value=100, value=0)

        with col2:
            st.subheader("Medical History")
            BPMeds = st.selectbox("On BP Medication?", options=[1.0, 0.0], format_func=lambda x: "Yes" if x == 1.0 else "No")
            prevalentStroke = st.selectbox("Previous Stroke?", options=[1, 0], format_func=lambda x: "Yes" if x == 1 else "No")
            prevalentHyp = st.selectbox("Hypertension?", options=[1, 0], format_func=lambda x: "Yes" if x == 1 else "No")
            diabetes = st.selectbox("Diabetes?", options=[1, 0], format_func=lambda x: "Yes" if x == 1 else "No")
            totChol = st.number_input("Total Cholesterol (mg/dL)", min_value=100, max_value=600, value=200)

        with col3:
            st.subheader("Current Vitals")
            sysBP = st.number_input("Systolic Blood Pressure", min_value=80, max_value=250, value=120)
            diaBP = st.number_input("Diastolic Blood Pressure", min_value=40, max_value=150, value=80)
            BMI = st.number_input("Body Mass Index (BMI)", min_value=10.0, max_value=60.0, value=25.0)
            heartRate = st.number_input("Heart Rate (BPM)", min_value=40, max_value=200, value=75)
            glucose = st.number_input("Glucose Level (mg/dL)", min_value=40, max_value=500, value=80)

        submit = st.form_submit_button("Run Prediction")

    if submit:
        # Create input DataFrame with correct column names from model metadata
        features = pd.DataFrame([[
            male, age, education, currentSmoker, cigsPerDay, BPMeds,
            prevalentStroke, prevalentHyp, diabetes, totChol, sysBP,
            diaBP, BMI, heartRate, glucose
        ]], columns=[
            'male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
            'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
            'diaBP', 'BMI', 'heartRate', 'glucose'
        ])

        # Prediction and Probability
        prediction = model.predict(features)[0]
        probability = model.predict_proba(features)[0][1]

        # Display Results
        st.markdown("---")
        if prediction == 1:
            st.error(f"### High Risk Detected")
            st.write(f"The model estimates a **{probability:.1%}** probability of heart disease.")
        else:
            st.success(f"### Low Risk Detected")
            st.write(f"The model estimates a **{probability:.1%}** probability of heart disease.")

        # Displaying the "Other X variables" as summary
        with st.expander("View Input Summary"):
            st.table(features)