# -*- coding: utf-8 -*-
"""Untitled64.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15eyVJc8LdfxuCSoIsQLlhW3sXX1A20ow
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# Set page configuration
st.set_page_config(page_title="Heart Disease Prediction", layout="centered")

# Load the trained model
@st.cache_resource
def load_model():
    # Ensure 'trained_model.joblib' is in the same directory
    return joblib.load('trained_model.joblib')

model = load_model()

st.title("❤️ Heart Disease Prediction")
st.write("Enter the patient details below to predict the risk of heart disease.")

# Create input fields based on the model's feature names
with st.form("prediction_form"):
    col1, col2, col3 = st.columns(3)

    with col1:
        male = st.selectbox("Gender", options=[0, 1], format_func=lambda x: "Male" if x == 1 else "Female")
        age = st.number_input("Age", min_value=1, max_value=120, value=40)
        education = st.selectbox("Education Level", options=[1, 2, 3, 4])
        currentSmoker = st.selectbox("Current Smoker", options=[0, 1], format_func=lambda x: "Yes" if x == 1 else "No")
        cigsPerDay = st.number_input("Cigarettes Per Day", min_value=0, max_value=100, value=0)

    with col2:
        BPMeds = st.selectbox("On BP Medication", options=[0, 1], format_func=lambda x: "Yes" if x == 1 else "No")
        prevalentStroke = st.selectbox("Prevalent Stroke", options=[0, 1], format_func=lambda x: "Yes" if x == 1 else "No")
        prevalentHyp = st.selectbox("Prevalent Hypertension", options=[0, 1], format_func=lambda x: "Yes" if x == 1 else "No")
        diabetes = st.selectbox("Diabetes", options=[0, 1], format_func=lambda x: "Yes" if x == 1 else "No")
        totChol = st.number_input("Total Cholesterol", min_value=100, max_value=600, value=200)

    with col3:
        sysBP = st.number_input("Systolic BP", min_value=80, max_value=250, value=120)
        diaBP = st.number_input("Diastolic BP", min_value=40, max_value=150, value=80)
        BMI = st.number_input("BMI", min_value=10.0, max_value=60.0, value=25.0)
        heartRate = st.number_input("Heart Rate", min_value=40, max_value=200, value=75)
        glucose = st.number_input("Glucose Level", min_value=40, max_value=500, value=80)

    submit = st.form_submit_button("Predict Risk")

if submit:
    # Create a DataFrame for the model
    input_data = pd.DataFrame([[
        male, age, education, currentSmoker, cigsPerDay, BPMeds,
        prevalentStroke, prevalentHyp, diabetes, totChol, sysBP,
        diaBP, BMI, heartRate, glucose
    ]], columns=[
        'male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
        'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
        'diaBP', 'BMI', 'heartRate', 'glucose'
    ])

    # Perform prediction
    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]

    st.divider()

    if prediction == 1:
        st.error(f"### High Risk Detected")
        st.write(f"The model predicts a **{probability:.2%}** probability of heart disease.")
    else:
        st.success(f"### Low Risk Detected")
        st.write(f"The model predicts a **{probability:.2%}** probability of heart disease.")